const AppError=require('../src/Error')
const passport=require('passport')
const GoogleStrategy = require('passport-google-oidc');
// const GoogleStrategy = require('passport-google-oauth20').Strategy;
const user=require('../models/user')
const authToken=require('../models/authToken')
const { ObjectId } = require('mongodb');
const { backend_url } = require('../src/variables');
require('dotenv').config()


// google sign in
// Error:provider.id cannot be mongoose.objectId because it is less than 24 character and 12 bytes
// to do generate token here and refresh token and then them 
// store cookie in the auth/google/callback
// for the id i look for google_id from the provider.id
// then when creating jwt i fetch for the _id generated by mongoose
// function for creating acces token and refresh token
const create_token=async (user_data)=>{
    // check for user
    const existing_user=await user.findOne({
        _id:user_data._id,
        provider:{$in:["google"]}
    })
    if(existing_user){
        const access_token=await existing_user.createjwt()
        const refresh_token=await existing_user.createRefreshToken()
        // store it in the db 
        await authToken.create({
                    user_id:existing_user._id,
                    token:refresh_token,
                    expiryDate:new Date(Date.now()+24*60*60*1000)
                })
                return {access_token,refresh_token}
    }
// create access token
// create refresh token
}
const authUser=async (issuer,profile,cb)=>{
    try{
        // converting the id to string
        console.log("profile",profile)
        // const string_id = profile.id.toString()
        // look here with name in the future i do have do change with id and find solution
        // console.log(issuer);
        // need to fix this ,one there is no user the id should be same as the id of google otherwise it will be conflict and not safe to look with names cz they are not unique 
        let existing_user=await user.findOne({google_id:profile.id})
        if(!existing_user){
            // check if email exist
            existing_user=await user.findOneAndUpdate({
                email:profile.emails[0].value
            },{
                $set:{
                username:profile.displayName,
                email:profile.emails[0].value,
                google_id:profile.id,
            },
             $addToSet:{
                        provider:"google",
                },
            },{
                new:true,
                upsert:true,
                setDefaultsOnInsert:true
            })
        }
            const user_data={
                _id:existing_user._id,
                email:existing_user.email,
                username:existing_user.username,
                role:existing_user.role
            }
            // probably the error here in cb when passing the object and renaming it
            // create access_token and refresh token then pass them within the 
            const {refresh_token,access_token}=await create_token(user_data)
            return cb(null,{user_data,access_token,refresh_token})
        // return cb(null,profile)
    }catch(err){
        // next(err)
        return cb(err,false)
    }
}

passport.use(new GoogleStrategy({
    clientID:process.env.GOOGLE_CLIENT_ID,
    clientSecret:process.env.GOOGLE_CLIENT_SECRET,
    callbackURL: `${backend_url}/auth/google/callback`,
    scope:['profile','email']
    }, authUser
));

